In [ ]:
!pip install google-play-scraper

Collecting google-play-scraper
  Downloading google-play-scraper-1.0.3.tar.gz (52 kB)
     |████████████████████████████████| 52 kB 871 kB/s
Building wheels for collected packages: google-play-scraper
  Building wheel for google-play-scraper (setup.py) ... done
  Created wheel for google-play-scraper: filename=google_play_scraper-1.0.3-py3-none-any.whl size=24394 sha256=2bce71781525a34d799427369a2ef086a84bc935afa9669c9b06b5336b0b0828
  Stored in directory: /root/.cache/pip/wheels/81/37/0b/4a14be55b449a048cd93d79930b1a980dee7896480defa1923
Successfully built google-play-scraper
Installing collected packages: google-play-scraper
Successfully installed google-play-scraper-1.0.3

In [ ]:
from google_play_scraper import app
import pandas as pd
import numpy as np

In [ ]:
from google_play_scraper import Sort, reviews_all
result = reviews_all(
    'com.telkom.indihome.external',
    sleep_milliseconds=0, 
    lang='id', 
    country='id', 
    sort=Sort.NEWEST, 
)

In [ ]:
df_busu = pd.DataFrame(np.array(result),columns=['review'])
df_busu = df_busu.join(pd.DataFrame(df_busu.pop('review').tolist()))
df_busu.head()

                                            reviewId  ... repliedAt
0  gp:AOqpTOG3ebrFbpuZDYbJYVoW7XRkNH_pDgkMvq7N5c1...  ...       NaT
1  gp:AOqpTOGyvrkotlY8XSg-w9oEN12YEf_Mx-WPkOo8pPO...  ...       NaT
2  gp:AOqpTOE1x9aDioKNrwHprnskRjSsMOlXRXuQ5pcYneI...  ...       NaT
3  gp:AOqpTOF0yxvRB11K1jPBrycI2wret8dE8K5UK2Cev8J...  ...       NaT
4  gp:AOqpTOHBgKiwdv55sgccaj-iAdFD60TcsrzOT2hWT0N...  ...       NaT

[5 rows x 10 columns]

In [ ]:
len(df_busu.index)

65066

In [ ]:
df_busu[['userName', 'score','at', 'content']].head()

         userName  ...                                            content
0       Rusdianto  ...                                                 Ok
1   Surya adnyana  ...                 Gak bisa dibuka sama sekali, parah
2      FAJAR ANTO  ...             Sangat membantu utk konfirmasi layanan
3  angga prasetyo  ...         Habiz up mala gak bisa liat pemakean kuota
4   Yulia Fatchur  ...  Apk burik, payah mau login aja gabisa Kalo gab...

[5 rows x 4 columns]

In [ ]:
new_df = df_busu[['userName', 'score','at', 'content']]
sorted_df = new_df.sort_values(by='at', ascending=False) 
sorted_df.head()

         userName  ...                                            content
0       Rusdianto  ...                                                 Ok
1   Surya adnyana  ...                 Gak bisa dibuka sama sekali, parah
2      FAJAR ANTO  ...             Sangat membantu utk konfirmasi layanan
3  angga prasetyo  ...         Habiz up mala gak bisa liat pemakean kuota
4   Yulia Fatchur  ...  Apk burik, payah mau login aja gabisa Kalo gab...

[5 rows x 4 columns]

In [ ]:
my_df = sorted_df[['userName', 'score','at', 'content']]

In [ ]:
my_df.head()

         userName  ...                                            content
0       Rusdianto  ...                                                 Ok
1   Surya adnyana  ...                 Gak bisa dibuka sama sekali, parah
2      FAJAR ANTO  ...             Sangat membantu utk konfirmasi layanan
3  angga prasetyo  ...         Habiz up mala gak bisa liat pemakean kuota
4   Yulia Fatchur  ...  Apk burik, payah mau login aja gabisa Kalo gab...

[5 rows x 4 columns]

In [ ]:
my_df.to_csv("ReviewMyIndihome.csv", index = False)